version: '3.5'
services:
  react:
    container_name: my-app
    build:
      context: .
      dockerfile: dev/Dockerfile
    volumes:
      - '.:/usr/app'
      - '/usr/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
